name: Check Twitch Stream

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install axios

      # 1. Restore the hidden notification history
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: notified.json
          key: bot-state-${{ github.run_id }}
          restore-keys: |
            bot-state-

      # 2. Run the bot
      - name: Run script
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TWITCH_GAME_ID: ${{ secrets.TWITCH_GAME_ID }}
        run: node index.js

      # 3. Save the new history invisibly for the next run
      - name: Save cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: notified.json
          key: bot-state-${{ github.run_id }}
